files:
  - source: '/kriolos-opos-app/src/main/resources/**/*.properties'
    ignore:
      - liquibase.properties
    translation: '/kriolos-opos-i18n/src/main/resources/**/%file_name%_%two_letters_code%.%file_extension%'
